In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('klasi.xlsx')
df


Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk Sesak Nafas  \
0       pr    50           155           56  tidak  tidak  tidak       tidak   
1       pr    31           154           60  tidak  tidak  tidak       tidak   
2       pr    32           163           56  tidak  tidak  tidak       tidak   
3       lk    21           165           53  tidak  tidak  tidak       tidak   
4       lk    33           166           62  tidak  tidak  tidak       tidak   
..     ...   ...           ...          ...    ...    ...    ...         ...   
243     pr    33           161           58     ya  tidak  tidak       tidak   
244     lk    29           164           59     ya  tidak  tidak       tidak   
245     lk    49           165           57     ya  tidak     ya       tidak   
246     pr    41           158           64  tidak  tidak  tidak       tidak   
247     lk    23           165           65  tidak  tidak  tidak       tidak   

    Keluhan Lain  Status  
0             ya       0  
1             ya       0  
2             ya       0  
3          tidak       0  
4             ya       0  
..           ...     ...  
243           ya       0  
244           ya       1  
245        tidak       1  
246           ya       0  
247           ya       0  

[248 rows x 10 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Gender        248 non-null    object
 1   Umur          248 non-null    int64 
 2   Tinggi Badan  248 non-null    int64 
 3   Berat Badan   248 non-null    int64 
 4   Pilek         248 non-null    object
 5   Demam         248 non-null    object
 6   Batuk         248 non-null    object
 7   Sesak Nafas   248 non-null    object
 8   Keluhan Lain  248 non-null    object
 9   Status        248 non-null    int64 
dtypes: int64(4), object(6)
memory usage: 19.5+ KB


In [3]:
N, D = df.shape
print('N: %d, D: %d' %(N, D))

N: 248, D: 10


In [4]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])
df['Pilek'] = encoder.fit_transform(df['Pilek'])
df['Demam'] = encoder.fit_transform(df['Demam'])
df['Batuk'] = encoder.fit_transform(df['Batuk'])
df['Sesak Nafas'] = encoder.fit_transform(df['Sesak Nafas'])
df['Keluhan Lain'] = encoder.fit_transform(df['Keluhan Lain'])

In [5]:
df

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  \
0         1    50           155           56      1      0      0   
1         1    31           154           60      1      0      0   
2         1    32           163           56      1      0      0   
3         0    21           165           53      1      0      0   
4         0    33           166           62      1      0      0   
..      ...   ...           ...          ...    ...    ...    ...   
243       1    33           161           58      2      0      0   
244       0    29           164           59      2      0      0   
245       0    49           165           57      2      0      1   
246       1    41           158           64      1      0      0   
247       0    23           165           65      1      0      0   

     Sesak Nafas  Keluhan Lain  Status  
0              0             1       0  
1              0             1       0  
2              0             1       0  
3              0             0       0  
4              0             1       0  
..           ...           ...     ...  
243            0             1       0  
244            0             1       1  
245            0             0       1  
246            0             1       0  
247            0             1       0  

[248 rows x 10 columns]

In [6]:
def ubah(v):
    if v == 1:
        return 0
    else:
        return 1
df['Pilek'] = df.Pilek.apply(ubah)

def ganti(w):
    if w == 1:
        return 0
    else:
        return 1
df['Gender'] = df.Gender.apply(ganti)

In [7]:
df

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  \
0         0    50           155           56      0      0      0   
1         0    31           154           60      0      0      0   
2         0    32           163           56      0      0      0   
3         1    21           165           53      0      0      0   
4         1    33           166           62      0      0      0   
..      ...   ...           ...          ...    ...    ...    ...   
243       0    33           161           58      1      0      0   
244       1    29           164           59      1      0      0   
245       1    49           165           57      1      0      1   
246       0    41           158           64      0      0      0   
247       1    23           165           65      0      0      0   

     Sesak Nafas  Keluhan Lain  Status  
0              0             1       0  
1              0             1       0  
2              0             1       0  
3              0             0       0  
4              0             1       0  
..           ...           ...     ...  
243            0             1       0  
244            0             1       1  
245            0             0       1  
246            0             1       0  
247            0             1       0  

[248 rows x 10 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gender        248 non-null    int64
 1   Umur          248 non-null    int64
 2   Tinggi Badan  248 non-null    int64
 3   Berat Badan   248 non-null    int64
 4   Pilek         248 non-null    int64
 5   Demam         248 non-null    int32
 6   Batuk         248 non-null    int32
 7   Sesak Nafas   248 non-null    int32
 8   Keluhan Lain  248 non-null    int32
 9   Status        248 non-null    int64
dtypes: int32(4), int64(6)
memory usage: 15.6 KB


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, df, test_size=0.25, random_state=2)
print(X_train.shape, y_train.shape)

(186, 10) (186, 10)


In [10]:
print(X_test.shape, y_test.shape)

(62, 10) (62, 10)


In [11]:
print(X_train)

     Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  \
18        0    33           157           57      0      0      0   
64        1    42           162           62      0      0      0   
5         0    30           162           54      0      0      0   
85        1    27           159           63      0      0      0   
2         0    32           163           56      0      0      0   
..      ...   ...           ...          ...    ...    ...    ...   
22        1    41           157           71      0      0      0   
72        1    42           160           69      0      0      0   
237       0    23           158           77      0      0      0   
15        1    32           166           66      0      0      0   
168       0    29           160           69      0      0      0   

     Sesak Nafas  Keluhan Lain  Status  
18             0             1       0  
64             0             1       0  
5              0             1       0  
85     

In [12]:
X_train1=X_train.values
X_train1=np.delete(X_train1, 9,axis=1)
y_train1=X_train['Status'].values
print(X_train1.shape)
print(X_train1)

(186, 9)
[[  0  33 157 ...   0   0   1]
 [  1  42 162 ...   0   0   1]
 [  0  30 162 ...   0   0   1]
 ...
 [  0  23 158 ...   0   0   0]
 [  1  32 166 ...   0   0   1]
 [  0  29 160 ...   0   0   0]]


In [13]:
X_test1=X_test.values
X_test1=np.delete(X_test1, 9, axis=1)
y_test1= X_test['Status'].values
print(X_test1.shape)
print(y_test1)

(62, 9)
[0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1
 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0]


In [14]:
from sklearn.preprocessing import MinMaxScaler
X_train1=MinMaxScaler().fit_transform(X_train1)
X_test1=MinMaxScaler().fit_transform(X_test1)
print(X_train1)
print(X_test1)

[[0.         0.25       0.21428571 ... 0.         0.         1.        ]
 [1.         0.4375     0.57142857 ... 0.         0.         1.        ]
 [0.         0.1875     0.57142857 ... 0.         0.         1.        ]
 ...
 [0.         0.04166667 0.28571429 ... 0.         0.         0.        ]
 [1.         0.22916667 0.85714286 ... 0.         0.         1.        ]
 [0.         0.16666667 0.42857143 ... 0.         0.         0.        ]]
[[1.         0.86666667 0.5        0.36       0.         0.
  0.         0.         0.        ]
 [1.         0.         0.625      0.44       0.         0.
  0.         0.         1.        ]
 [0.         0.44444444 0.625      0.44       0.         0.
  0.         0.         0.        ]
 [1.         0.02222222 0.6875     0.48       0.         0.
  0.         0.         1.        ]
 [1.         0.28888889 0.6875     0.4        0.         0.
  0.         0.         1.        ]
 [1.         0.24444444 0.625      0.28       0.         0.
  0.         0. 

In [15]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(9, activation='relu', input_shape=(9,)))

model.add(Dense(10, activation='relu'))


model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 9)                 90        
                                                                 
 dense_1 (Dense)             (None, 10)                100       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X_train1, y_train1, epochs=200, verbose=1, batch_size=20)

y_pred = model.predict(X_test1)
y_pred = y_pred >= 0.15

Epoch 1/200
10/10 [==============================] - 2s 7ms/step - loss: 0.6283 - accuracy: 0.7527
Epoch 2/200
10/10 [==============================] - 0s 4ms/step - loss: 0.6065 - accuracy: 0.7742
Epoch 3/200
10/10 [==============================] - 0s 3ms/step - loss: 0.5891 - accuracy: 0.7849
Epoch 4/200
10/10 [==============================] - 0s 4ms/step - loss: 0.5731 - accuracy: 0.7903
Epoch 5/200
10/10 [==============================] - 0s 4ms/step - loss: 0.5591 - accuracy: 0.7903
Epoch 6/200
10/10 [==============================] - 0s 4ms/step - loss: 0.5462 - accuracy: 0.7903
Epoch 7/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5338 - accuracy: 0.8011
Epoch 8/200
10/10 [==============================] - 0s 4ms/step - loss: 0.5236 - accuracy: 0.8011
Epoch 9/200
10/10 [==============================] - 0s 4ms/step - loss: 0.5130 - accuracy: 0.8065
Epoch 10/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5043 - accuracy: 0.8172
Epoch 11/

10/10 [==============================] - 0s 3ms/step - loss: 0.2752 - accuracy: 0.9086
Epoch 84/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2746 - accuracy: 0.9086
Epoch 85/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2742 - accuracy: 0.9086
Epoch 86/200
10/10 [==============================] - 0s 5ms/step - loss: 0.2735 - accuracy: 0.9086
Epoch 87/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2729 - accuracy: 0.9086
Epoch 88/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2726 - accuracy: 0.9086
Epoch 89/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2729 - accuracy: 0.9086
Epoch 90/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2713 - accuracy: 0.9086
Epoch 91/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2707 - accuracy: 0.9086
Epoch 92/200
10/10 [==============================] - 0s 5ms/step - loss: 0.2701 - accuracy: 0.9086
Epoch 93/200


10/10 [==============================] - 0s 4ms/step - loss: 0.2374 - accuracy: 0.9194
Epoch 165/200
10/10 [==============================] - 0s 5ms/step - loss: 0.2372 - accuracy: 0.9194
Epoch 166/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2371 - accuracy: 0.9194
Epoch 167/200
10/10 [==============================] - 0s 3ms/step - loss: 0.2371 - accuracy: 0.9140
Epoch 168/200
10/10 [==============================] - 0s 3ms/step - loss: 0.2368 - accuracy: 0.9140
Epoch 169/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2358 - accuracy: 0.9140
Epoch 170/200
10/10 [==============================] - 0s 3ms/step - loss: 0.2360 - accuracy: 0.9194
Epoch 171/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2360 - accuracy: 0.9194
Epoch 172/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2354 - accuracy: 0.9194
Epoch 173/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2346 - accuracy: 0.9194
Epoc

In [18]:
y_test

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  \
186       1    60           162           61      0      0      0   
90        1    21           164           63      0      0      0   
165       0    41           164           63      0      0      0   
166       1    22           165           64      0      0      0   
91        1    34           165           62      0      0      0   
..      ...   ...           ...          ...    ...    ...    ...   
6         1    26           159           66      0      0      0   
28        0    57           161           58      0      0      0   
12        1    57           166           57      0      0      0   
29        1    38           165           56      1      0      1   
89        0    24           161           65      0      1      0   

     Sesak Nafas  Keluhan Lain  Status  
186            0             0       0  
90             0             1       1  
165            0             0       0  
166            0             1       1  
91             0             1       0  
..           ...           ...     ...  
6              0             0       0  
28             0             0       0  
12             0             1       0  
29             0             0       1  
89             0             1       0  

[62 rows x 10 columns]

In [19]:
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(hidden_layer_sizes=10, learning_rate_init=0.1, max_iter=100)
clf.fit(X_train1, y_train1)

C:\Users\By\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:679: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=10, learning_rate_init=0.1, max_iter=100)

In [20]:
y_pred=clf.predict(X_test1)
from sklearn.metrics import accuracy_score,confusion_matrix
round(accuracy_score(y_test1, y_pred), 3)

0.919

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test1, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        45
           1       0.93      0.76      0.84        17

    accuracy                           0.92        62
   macro avg       0.92      0.87      0.89        62
weighted avg       0.92      0.92      0.92        62



In [22]:
confusion_matrix(y_test1, y_pred)

array([[44,  1],
       [ 4, 13]], dtype=int64)

In [23]:
hasil = {'pred':y_pred,'actual':y_test1}
hasil = pd.DataFrame(hasil)

In [27]:
hasil.to_excel('hasil.xlsx')