In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('klass.xlsx')
df.head()

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  Sesak Nafas  \
0       0    50           155           56      0      0      0            0   
1       0    31           154           60      0      0      0            0   
2       1    32           163           56      0      0      0            0   
3       1    21           165           53      0      0      0            0   
4       1    33           166           62      0      0      0            0   

   Keluhan Lain  Status  
0             1       0  
1             1       0  
2             1       0  
3             0       0  
4             1       0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gender        248 non-null    int64
 1   Umur          248 non-null    int64
 2   Tinggi Badan  248 non-null    int64
 3   Berat Badan   248 non-null    int64
 4   Pilek         248 non-null    int64
 5   Demam         248 non-null    int64
 6   Batuk         248 non-null    int64
 7   Sesak Nafas   248 non-null    int64
 8   Keluhan Lain  248 non-null    int64
 9   Status        248 non-null    int64
dtypes: int64(10)
memory usage: 19.5 KB


In [3]:
N, D = df.shape
print('N: %d, D: %d' %(N, D))

N: 248, D: 10


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, df, test_size=0.25, random_state=2)
print(X_train.shape, y_train.shape)

(186, 10) (186, 10)


In [17]:
print(X_test.shape, y_test.shape)

(62, 10) (62, 10)


In [18]:
print(X_train)

     Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  \
18        0    33           157           57      0      0      0   
64        1    42           162           62      1      1      0   
5         0    30           162           54      0      0      0   
85        1    27           159           63      0      0      0   
2         1    32           163           56      0      0      0   
..      ...   ...           ...          ...    ...    ...    ...   
22        1    41           157           71      0      0      0   
72        1    42           160           69      0      0      0   
237       0    23           158           77      0      0      0   
15        1    32           166           66      0      0      0   
168       0    29           160           69      0      0      0   

     Sesak Nafas  Keluhan Lain  Status  
18             0             1       0  
64             0             1       1  
5              0             1       0  
85     

In [19]:
X_train1=X_train.values
X_train1=np.delete(X_train1, 9,axis=1)
y_train1=X_train['Status'].values
print(X_train1.shape)
print(X_train1)

(186, 9)
[[  0  33 157 ...   0   0   1]
 [  1  42 162 ...   0   0   1]
 [  0  30 162 ...   0   0   1]
 ...
 [  0  23 158 ...   0   0   0]
 [  1  32 166 ...   0   0   1]
 [  0  29 160 ...   0   0   0]]


In [20]:
X_test1=X_test.values
X_test1=np.delete(X_test1, 9, axis=1)
y_test1= X_test['Status'].values
print(X_test1.shape)
print(y_test1)

(62, 9)
[0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1
 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0]


In [21]:
from sklearn.preprocessing import MinMaxScaler
X_train1=MinMaxScaler().fit_transform(X_train1)
X_test1=MinMaxScaler().fit_transform(X_test1)
print(X_train1)
print(X_test1)

[[0.         0.25       0.21428571 ... 0.         0.         1.        ]
 [1.         0.4375     0.57142857 ... 0.         0.         1.        ]
 [0.         0.1875     0.57142857 ... 0.         0.         1.        ]
 ...
 [0.         0.04166667 0.28571429 ... 0.         0.         0.        ]
 [1.         0.22916667 0.85714286 ... 0.         0.         1.        ]
 [0.         0.16666667 0.42857143 ... 0.         0.         0.        ]]
[[1.         0.86666667 0.5        0.36       0.         0.
  0.         0.         0.        ]
 [1.         0.         0.625      0.44       0.         0.
  0.         0.         1.        ]
 [0.         0.44444444 0.625      0.44       0.         0.
  0.         0.         0.        ]
 [1.         0.02222222 0.6875     0.48       0.         0.
  0.         0.         1.        ]
 [1.         0.28888889 0.6875     0.4        0.         0.
  0.         0.         1.        ]
 [1.         0.24444444 0.625      0.28       0.         0.
  0.         0. 

In [22]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(12, activation='relu', input_shape=(9,)))

model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 12)                120       
                                                                 
 dense_5 (Dense)             (None, 8)                 104       
                                                                 
 dense_6 (Dense)             (None, 8)                 72        
                                                                 
 dense_7 (Dense)             (None, 1)                 9         
                                                                 
Total params: 305
Trainable params: 305
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.fit(X_train1, y_train1, epochs=200, verbose=1, batch_size=20)

y_pred = model.predict(X_test1)
y_pred = y_pred >= 0.15

Epoch 1/200
10/10 [==============================] - 1s 4ms/step - loss: 0.6828 - accuracy: 0.7634
Epoch 2/200
10/10 [==============================] - 0s 3ms/step - loss: 0.6447 - accuracy: 0.7634
Epoch 3/200
10/10 [==============================] - 0s 6ms/step - loss: 0.5916 - accuracy: 0.7634
Epoch 4/200
10/10 [==============================] - 0s 6ms/step - loss: 0.5471 - accuracy: 0.7634
Epoch 5/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5157 - accuracy: 0.7634
Epoch 6/200
10/10 [==============================] - 0s 5ms/step - loss: 0.4878 - accuracy: 0.7688
Epoch 7/200
10/10 [==============================] - 0s 4ms/step - loss: 0.4648 - accuracy: 0.7742
Epoch 8/200
10/10 [==============================] - 0s 7ms/step - loss: 0.4432 - accuracy: 0.7849
Epoch 9/200
10/10 [==============================] - 0s 4ms/step - loss: 0.4245 - accuracy: 0.8280
Epoch 10/200
10/10 [==============================] - 0s 5ms/step - loss: 0.4088 - accuracy: 0.8656
Epoch 11/

10/10 [==============================] - 0s 3ms/step - loss: 0.2082 - accuracy: 0.9301
Epoch 84/200
10/10 [==============================] - 0s 3ms/step - loss: 0.2061 - accuracy: 0.9301
Epoch 85/200
10/10 [==============================] - 0s 2ms/step - loss: 0.2081 - accuracy: 0.9301
Epoch 86/200
10/10 [==============================] - 0s 3ms/step - loss: 0.2070 - accuracy: 0.9301
Epoch 87/200
10/10 [==============================] - 0s 2ms/step - loss: 0.2075 - accuracy: 0.9301
Epoch 88/200
10/10 [==============================] - 0s 3ms/step - loss: 0.2085 - accuracy: 0.9301
Epoch 89/200
10/10 [==============================] - 0s 2ms/step - loss: 0.2100 - accuracy: 0.9301
Epoch 90/200
10/10 [==============================] - 0s 3ms/step - loss: 0.2054 - accuracy: 0.9301
Epoch 91/200
10/10 [==============================] - 0s 4ms/step - loss: 0.2093 - accuracy: 0.9301
Epoch 92/200
10/10 [==============================] - 0s 7ms/step - loss: 0.2056 - accuracy: 0.9301
Epoch 93/200


10/10 [==============================] - 0s 2ms/step - loss: 0.1875 - accuracy: 0.9301
Epoch 165/200
10/10 [==============================] - 0s 2ms/step - loss: 0.1842 - accuracy: 0.9301
Epoch 166/200
10/10 [==============================] - 0s 2ms/step - loss: 0.1860 - accuracy: 0.9301
Epoch 167/200
10/10 [==============================] - 0s 2ms/step - loss: 0.1832 - accuracy: 0.9301
Epoch 168/200
10/10 [==============================] - 0s 2ms/step - loss: 0.1837 - accuracy: 0.9301
Epoch 169/200
10/10 [==============================] - 0s 3ms/step - loss: 0.1873 - accuracy: 0.9355
Epoch 170/200
10/10 [==============================] - 0s 4ms/step - loss: 0.1845 - accuracy: 0.9355
Epoch 171/200
10/10 [==============================] - 0s 3ms/step - loss: 0.1834 - accuracy: 0.9355
Epoch 172/200
10/10 [==============================] - 0s 4ms/step - loss: 0.1826 - accuracy: 0.9301
Epoch 173/200
10/10 [==============================] - 0s 4ms/step - loss: 0.1860 - accuracy: 0.9355
Epoc

In [25]:
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)
clf.fit(X_train1, y_train1)

C:\Users\By\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:679: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)

In [26]:
y_pred=clf.predict(X_test1)
from sklearn.metrics import accuracy_score
round(accuracy_score(y_test1, y_pred), 3)

0.919

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test1, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        46
           1       0.92      0.75      0.83        16

    accuracy                           0.92        62
   macro avg       0.92      0.86      0.89        62
weighted avg       0.92      0.92      0.92        62

